services:
  wordpress:
    image: wordpress:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - mysqldb
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL','/');
      # define('WP_HOME','/');
    # volumes:
    #   - wordpress:/var/www/html
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'




      
#     volumes:
#       - db:/var/lib/mysql

# volumes:
#   wordpress:
#   db:
